version: '3'
services:
  database:
    image: postgis/postgis:13-3.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spatial_data_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    healthcheck:
      test: "exit 0"

  alembic:
    build:  
      context: ./
      dockerfile: ./etl_app/Dockerfile
    environment:
      DATABASE_URL: postgresql://username:password@database:5432/spatial_data_db
    command: ["bash", "-c", "alembic upgrade head && python app.py"]
    depends_on:
      database:
        condition: service_healthy
    networks:
      - mynetwork

  fastapi:
      build:
        context: ./
        dockerfile: ./server_app/Dockerfile
      environment:
        DATABASE_PLANET_URL: postgresql://username:password@database:5432/spatial_data_db
      depends_on:
        database:
          condition: service_healthy
      ports:
        - 3200:8000
      volumes:
        - .:/usr/src/app/geo_app
      networks:
        - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge